export const endpoints = {
  login: "authentication",
  myBookings: "Booking/sport/bookings/calender/",
  getMyProfile: "Account/user/profile/info/record",
  validate: "Authentication/user/validate",
  getAccountInfo: "Booking/sport/bookings/info",
  getSubscriptionData: "Subscription/sport/member/subscription/info",
  getNotifications: "Notification/sport/member/notifications",
  getCalendarData: "Booking/sport/tennis/booking/",
  getSportServices: "SportServices/sport/services",
  addToFavorite: "Member/sport/members/setfavourite",
  confirmBooking: "Booking/sport/booking/confirmation",
  cancelBooking: "Booking/sport/booking/Cancel",
  getAlreadyBookedDetails: "Booking/sport/booking/details/",
  topupBalance: "Payment/sport/topup",
  balance: "account/sport/member/info/balance",
  updateProfile: "Account/user/profile",
  updateUserInfo: "Account/user/profile/info",
  contactus: "Common/sport/help/contactus",
  changePass: "Authentication/user/reset/password",
  changePin: "Authentication/user/reset/pincode",
};
