export const endpoints = {
  login: "authentication",
  myBookings: "Booking/sport/bookings/calender/",
  getMyProfile: "Account/user/profile/info/record",
  getAccountInfo: "Booking/sport/bookings/info",
  getSubscriptionData: "Subscription/sport/member/subscription/info",
  getNotifications: "Notification/sport/member/notifications",
  getCalendarData: "Booking/sport/tennis/booking/",
  getSportServices: "SportServices/sport/services",
  addToFavorite: "Member/sport/members/setfavourite",
  confirmBooking: "Booking/sport/booking/confirmation",
  cancelBooking: "Booking/sport/booking/Cancel",
  getAlreadyBookedDetails: "Booking/sport/booking/details/",
  topupBalance: "Payment/sport/topup",
};
